### ISSUE TITLE
Impossible to connect

### ISSUE THREAD

**Issue by ernesst** [bhdouglass/owncloud-files-scope#1]
Hello,

Thank a lot for your work with this promising scope. 
I'm currently not able to use it because i cannot connect. 

Does this scope works with secure connection ? 

When I'm entering 
https://owncloud_address => i got an "this folder is empty"
owncloud_address=> Nothing appears. 

Moreover in your address example you wrote ownccloud instead of owncloud.

Regards

**Comment by wayneward** [comment]
again yes looks great but cant connect 
ive tried it with http on the beginning of the url and with out
i get the photo attached
im also doing work on owncloud with touch if you want to come chat with us on telegram were on the ubuntu social group be nice to chat - like the idea of owncloud scopes :)
like if there is music it on the owncloud will it play or videos...

![photo_2016-02-29_13-48-31](https://cloud.githubusercontent.com/assets/11428255/13396255/85297c3c-deeb-11e5-993f-1404f2e7ccd1.jpg)

**Comment by bhdouglass** [comment]
Thanks for trying out my new scope! I'll have to update the example url as you'll want to include `https://`. Are you including `/remote.php/webdav` at the end of your url? Also, if you have a self-signed certificate it may not work, I changed my certificate to one from https://letsencrypt.org/ .

**Comment by bhdouglass** [comment]
@wayneward which telegram group is that? I'm a part of several different ones.
Unfortunately it doesn't do music or videos yet, but that would be pretty awesome.

**Comment by wayneward** [comment]
ah confirmed it works with /remote.php/webdav on the end of the URL 
nice work :+1: 
were here on telegram https://telegram.me/joinchat/A7yL8QUE1tibuVXmps6hmg

**Comment by bhdouglass** [comment]
I've just uploaded v1.3 to the Ubuntu App Store, it will now try to correct your url if you leave off `/remote.php/webdav`. I've also joined the Ubuntu Social group :)
If you guys have any other problems let me know!

**Comment by wayneward** [comment]
perfect ill give it a whirl nice work 
talk soon :)
