### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by leodumont** [bhdouglass/owncloud-files-scope#12]
Hello,
Thanks for your work, can you post some installation instructions (or maybe a link to a documentation ) ? I'm new to ubuntu touch (on the recent BQ Aquaris M10 tablet) and I'm quite unfamiliar with the installation of scopes outside of the official market.

Thanks in advance,

**Comment by bhdouglass** [comment]
If you wanted to compile it yourself you could, it's simple enough. But you can find this scope in the app store - https://uappexplorer.com/app/owncloud-files-scope.bhdouglass . I should probably add that link to the README file or something.
