### ISSUE TITLE
DAV link needs changing

### ISSUE THREAD

**Issue by sh2515** [bhdouglass/owncloud-files-scope#13]
The DAV address seems to be faulty.
Putting HTTPS or http://example.com/owncloud/remite.php/webdav/
Doesn't work on OC 9. You can see the folders but not the files in them
The format needs to be
HTTPS or http://example.com/owncloud/remote.php/dav/files/username/

The same occurs when on a desktop. However on Ubuntu touch when you type the correct format, no folders or files are shown.

https://doc.owncloud.org/server/9.0/user_manual/files/access_webdav.html

**Comment by bhdouglass** [comment]
Thank you for the heads up! I'll put this in my next version (coming soonish).

**Comment by bhdouglass** [comment]
I've just released v1.8 that has ownCloud 9 support. Let me know if it gives you any issues!
