### ISSUE TITLE
Second level hierarchy site

### ISSUE THREAD

**Issue by guiyou65** [bhdouglass/owncloud-files-scope#14]
Hello, my owncloud site is not at the top of my domain name hierarchy : https://mysite.com/owncloud/
So the app connects to my site, I can see the files directories, but when I click one, the app cannot find files with error message "/owncloud/directory not found".
Hope this will be fixed. This is a very nice app !

**Comment by bhdouglass** [comment]
Are you using ownCloud v9? I've had reports (issue #13 ) that the scope doesn't work properly with ownCloud v9. I'm currently working on a new version with ownCloud v9 support.

**Comment by guiyou65** [comment]
Yes I am ! Sorry I did'nt see the issue #13, or did'nt connect it with 
mine.
Thanks for your quick answer and for your work.
Thierry 


Le lundi 2 mai 2016 06:11:39 CEST, Brian Douglass 
<notifications@github.com> a écrit :
> Are you using ownCloud v9? I've had reports (issue #13 ) that 
> the scope doesn't work properly with ownCloud v9. I'm currently 
> working on a new version with ownCloud v9 support.
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/bhdouglass/owncloud-files-scope/issues/14#issuecomment-216102244


-- 
Message envoyé via Dekko depuis mon appareil Ubuntu

**Comment by bhdouglass** [comment]
No worries! I'll close this issue out now, and when I release the next version I'll close out the other.
