### ISSUE TITLE
Cannot access self-signed https servers

### ISSUE THREAD

**Issue by hsuutari** [bhdouglass/owncloud-files-scope#15]
The client does not allow to access self-signed webservers. I think most home users are using self-signed certs on their home computers. Makes the scope unusable currently, so there should be a possibility to override permanently.

**Comment by bhdouglass** [comment]
I recommend using a free certificate from letsencrypt.org. But in the absence of that if you are running the latest version of the scope (v1.8) you can use the new option called "Allow self signed certificate" that should allow you to connect to your server using a self signed certificate.
