### ISSUE TITLE
Folder not found

### ISSUE THREAD

**Issue by Leon083** [bhdouglass/owncloud-files-scope#16]
When i try to connect, it founds the parent folder, for example, documents folder, but if i tap on this folder it didn't find any file. This happen because the link (/owncloud/documents) doesn't exist: i have to modify it manually in /documents (removing /owncloud) and then it works.
If i try to remove /owncloud in the webdav settings, it doesn't find anything.

**Comment by bhdouglass** [comment]
What does your owncloud URL look like?

**Comment by Leon083** [comment]
https://example.noip.me/owncloud

**Comment by bhdouglass** [comment]
Thank you! I see where the problem is, I'll get it fixed ASAP.

**Comment by Leon083** [comment]
Thank you! Great work, this is what a scope should be like.

**Comment by bhdouglass** [comment]
I've just uploaded v1.91 to the store, let me know if that works for you!

**Comment by Leon083** [comment]
It works! Thank you so much!!

**Comment by bhdouglass** [comment]
You're welcome!
