### ISSUE TITLE
no download

### ISSUE THREAD

**Issue by gianlucazaramella** [bhdouglass/owncloud-files-scope#17]
Server oc 8.1.8
ubuntu touch ota 11
scope 9.91
self signed certificate
I can see folders and files. When I try to download, the browser ask me for signed certificate and more information. I go on. 
then I'm not able to download the file nor to open it by a reader or libre office. The app stops working without any error message. 
I have to say that I'm able to use owncloud with the browser firefox in desktop mode. With the standard browser is not possible to authenticate.
thank you

**Comment by bhdouglass** [comment]
The standard Ubuntu Touch browser might be more restrictive that Firefox when it comes to self signed certificates. Unfortunately there isn't much I can do other than recommend that you get a regular certificate (like a free one from https://letsencrypt.org ).
