### ISSUE TITLE
Special character / login issue

### ISSUE THREAD

**Issue by ernesst** [bhdouglass/owncloud-files-scope#2]
I found with the help of Marius, why the i'm not able to log with the scope to my owncloud : special character

My password has special characters like = - & $ % => impossible to connect
I remove the special character only digit, lower and upper case => able to connect to my owncloud.

Thanks

**Comment by bhdouglass** [comment]
I've just uploaded v1.3 to the app store, it has a fix that will allow you to use the special characters in the username or password. Let me know if you have any other issues!
