### ISSUE TITLE
Empty folders in Google Drive external storage

### ISSUE THREAD

**Issue by dani-arde** [bhdouglass/owncloud-files-scope#4]
Hello and thanks for this very nice scope. I noticed that on my Google Drive folder, mounted in owncloud with the external storage, every folder that has a space in its name show up as empty (including the very same Google Drive root folder).

**Comment by dani-arde** [comment]
I forgot to mention that this does not happen with Dropbox, but I didn't test other services.

**Comment by bhdouglass** [comment]
I've just released v1.4 to the app store. This _should_ fix your problem, as it fixes folders with spaces in their names appearing as empty.

**Comment by bhdouglass** [comment]
Please let me know if this fixes it for you.

**Comment by dani-arde** [comment]
Yes, it is fixed. Thank you very much.
However I noticed that the same thing happens when the folder name contains special characters like "&".

**Comment by bhdouglass** [comment]
Thanks for pointing that out! I've just uploaded v1.5 to the app store. This covers issues with special characters like &. Let me know if that fixes your problem!

**Comment by dani-arde** [comment]
Awesome! Thank you!

**Comment by bhdouglass** [comment]
Feel free to contact me again if you have any other issues!
