### ISSUE TITLE
Preview images (feature request)

### ISSUE THREAD

**Issue by MariusQuabeck** [bhdouglass/owncloud-files-scope#7]
This is a future feature request.
Would it be possible to display the preview images for the pictures in the scope?
Owncloud itself already created a folder with preview images/thumbnails.
It's located at /data/*user*/thumbnails

**Comment by bhdouglass** [comment]
This has been on my todo list! I will look into it.

**Comment by bhdouglass** [comment]
I uploaded v1.6 to the store last night, it has image and audio previews!
